# Generated by Django 5.0.2 on 2024-03-23 13:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "pos_system",
            "0003_productunit_rename_stock_quantity_product_stock_qty_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductUnit",
            new_name="Unit",
        ),
        migrations.AlterModelOptions(
            name="unit",
            options={"verbose_name": "Unit", "verbose_name_plural": "Units"},
        ),
        migrations.AlterModelTable(
            name="unit",
            table="unit",
        ),
    ]
