# Generated by Django 5.0.2 on 2024-03-23 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pos_system", "0004_rename_productunit_unit_alter_unit_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="company",
        ),
        migrations.AddField(
            model_name="unit",
            name="code",
            field=models.CharField(default="a", max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_qty",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Stock Quantity"
            ),
        ),
        migrations.CreateModel(
            name="ProductQtyChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("from_qty", models.PositiveIntegerField()),
                ("to_qty", models.PositiveIntegerField()),
                ("change_type", models.CharField(max_length=50)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pos_system.product",
                    ),
                ),
            ],
        ),
    ]
