# Generated by Django 5.0.2 on 2024-03-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pos_system", "0005_remove_orderproduct_company_unit_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="original_price",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="price",
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
