# Generated by Django 5.0.2 on 2024-03-31 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pos_system",
            "0007_remove_product_count_in_box_remove_product_price_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="count_in_box",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="stock_qty",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=10,
                verbose_name="Stock Quantity",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="pos_system.unit",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ProductQtyChange",
        ),
    ]
