# Generated by Django 5.0.2 on 2024-03-31 06:16

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pos_system",
            "0008_product_count_in_box_product_price_product_stock_qty_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="courier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="orderlog",
            name="order",
        ),
        migrations.AlterField(
            model_name="consumer",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="consumer",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="Full Name"),
        ),
        migrations.AlterField(
            model_name="consumer",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="Phone Number"
            ),
        ),
        migrations.DeleteModel(
            name="Courier",
        ),
        migrations.DeleteModel(
            name="OrderLog",
        ),
    ]
