# Generated by Django 5.0.2 on 2024-03-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_company_user_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("owner", "Owner"), ("courier", "Courier")],
                max_length=255,
                null=True,
            ),
        ),
    ]
