# Generated by Django 5.0.2 on 2024-03-31 06:01

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
